#file: noinspection SpellCheckingInspection
#testonly: False
with-expecter: True
packages:
  github.com/evorts/kevlars/algo:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/audit:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/config:
    config:
      all: False
      include-regex: ".*(Manager|Provider)$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/csmtp:
    config:
      all: False
      include-regex: ".*Client$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/db:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/inmemory:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/logger:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/rpc:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/scheduler:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/telemetry:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/ctime:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False
  github.com/evorts/kevlars/validation:
    config:
      all: False
      include-regex: ".*Manager$"
      recursive: True
      filename: "mock_{{.InterfaceNameLower}}.go"
      dir: ./mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
      mockname: "{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: False