// Code generated by mockery v2.43.0. DO NOT EDIT.

package config

import mock "github.com/stretchr/testify/mock"

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// GetData provides a mock function with given fields:
func (_m *Provider) GetData() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Provider_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type Provider_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *Provider_Expecter) GetData() *Provider_GetData_Call {
	return &Provider_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *Provider_GetData_Call) Run(run func()) *Provider_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_GetData_Call) Return(_a0 map[string]interface{}) *Provider_GetData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_GetData_Call) RunAndReturn(run func() map[string]interface{}) *Provider_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function with given fields:
func (_m *Provider) Init() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Provider_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type Provider_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *Provider_Expecter) Init() *Provider_Init_Call {
	return &Provider_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *Provider_Init_Call) Run(run func()) *Provider_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Init_Call) Return(_a0 error) *Provider_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Provider_Init_Call) RunAndReturn(run func() error) *Provider_Init_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
