app:
  name: "sample_app"
  version: "1.0.0"
  port:
    rest: 9999
    grpc: 8899
  graceful_timeout: "30s"
  healthcheck:
    health: true # /health
    metrics: true # /health/metrics
    dependencies: true # /health/dependencies
  log:
    level: 4 # // 0 = PANIC, 1 = FATAL, 2 = ERROR, 3 = WARN, 4 = INFO, 5 = DEBUG, 6 = TRACE
    tz: "Asia/Jakarta"
    use_local_tz: true # default to Asia/Jakarta

#### Open Telemetry Section ####
telemetry:
  name: "sample_telemetry_name"
  tracing:
    enabled: true
    body_tracing_enabled: true
    skip_endpoints:
      - "/health"
      - "/health/metrics"
      - "/health/dependencies"
    providers:
      - "standard" # using OTLP format
      - "zipkin"
    standard:
      address: "http://localhost:14268/api/traces"
    zipkin:
      address: "http://localhost:9411/api/v2/spans"
      log_name: "zipkin-service-log"
  metrics:
    enabled: true
    providers:
      - "datadog"
    datadog:
      sample_rate: 1.0
      address: "dd-agent:8125"

#### GRPC Client ####
grpc:
  name: "grpc_client"
  telemetry_enabled: true
  metric_enabled: true
  services:
    - name: "sample_grpc_service"
      service_url: ""
      log_request_payload: true
      log_request_payload_in_json: true
      circuit_breaker:
        timeout: 10000 #general timeout

#### Databases Section ####
dbs:
  sample_db1:
    max_open_connection: 50
    max_idle_connection: 30
    telemetry_enabled: true
  audit_db:
    max_open_connection: 50
    max_idle_connection: 30
    telemetry_enabled: false

#### Caches Section ####
caches:
  default:
    enabled: true
    telemetry_enabled: true
  other:
    enabled: false
    telemetry_enabled: false

#### Audit Log Section ####
audit:

#### Queue Section ####
queues:

#### Scheduler [Multiple] Section ####
schedulers:
  default: # this config will be used when using StartAsDaemon
    pattern: ""
    support_seconds: false
    enabled: true
  sample_schedule:
    pattern: ""
    support_seconds: false
    enabled: true

#### Algorithm Section ####
similarity:
  simple_date:
    - key: "dob"
      weight: 0.25
      matchers:
        # [similar part count, match percentage]
        - [1, 0.4]
        - [2, 0.6]
        - [3, 1.0]
  jaro_winkler:
    - key: "full_name"
      weight: 0.35
  levenshtein:
    - key: "ktp"
      weight: 0.4
      matchers:
        # [replacement count, match percentage]
        - [ 0, 1.0 ]
        - [ 1, 0.8 ]
        - [ 2, 0.6 ]
        - [ 3, 0.4 ]
